### PR TITLE
Docker run fix

### PR DESCRIPTION
**Pull request by JayJay1989**
Add java.policy inside the jar itself to be able to run it in a docker container

### CODE REVIEW

**Comment by tterrag1098** [comment]
Does this make the current way of installing a policy redundant?

**Comment by JayJay1989** [comment]
yes it is. For some reason java don't take the policy in a docker container. The only solution was to implement it

**Comment by tterrag1098** [comment]
So go ahead and include removing the file and the instructions in the readme as part of this PR

**Comment by JayJay1989** [comment]
Done.

**Comment by tterrag1098** [comment]
I think you messed something up with the rebase?

**Comment by tterrag1098** [comment]
Nevermind, tested locally and seems great, thanks! Sorry for the huge delay, I've been super busy (and traveling!)

**Comment by JayJay1989** [comment]
> I think you messed something up with the rebase?

Thats what i thought at first.

> Nevermind, tested locally and seems great, thanks! Sorry for the huge delay, I've been super busy (and traveling!)

Not a problem at all.

**Pull request merged**
